- repo: git://github.com/moia-dev/pre-commit-terraform
  sha: v1.7.3
  hooks:
    - id: terraform_fmt
- repo: git://github.com/moia-dev/pre-commit-terraform-vars
  sha: master
  hooks:
    - id: terraform-vars
