apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::AWS_ACCOUNT_ID:user/AWS_IAM_USER
      username: AWS_IAM_USER
      groups:
        - system:masters