apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: REPLACE_WITH_ARN_INSTANCE_PROFILE_ROLE
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - userarn: arn:aws:iam::AWS_ACCOUNT_ID:user/AWS_IAM_USER
      username: AWS_IAM_USER
      groups:
        - system:masters
